import { NextRequest } from 'next/server';
import { requireAuth, authErrorResponse } from '@/lib/auth-middleware';
import { mapAnalyzeResponse } from '@/lib/omniplan-utils';
import { db } from '@/db';
import { projects, projectMembers, tasks, links, resources } from '@/db/schema';

const CONVERTER_URL = process.env.CONVERTER_URL ?? 'http://localhost:7860';

export async function POST(req: NextRequest): Promise<Response> {
  let user;
  try {
    user = await requireAuth(req);
  } catch (err) {
    return authErrorResponse(err);
  }

  try {
    const formData = await req.formData();
    const file = formData.get('file');
    if (!file || !(file instanceof File)) {
      return Response.json({ error: 'Missing file field' }, { status: 400 });
    }

    // Forward the file to the Flask converter /analyze endpoint
    const converterForm = new FormData();
    converterForm.append('file', file);

    const converterRes = await fetch(`${CONVERTER_URL}/analyze`, {
      method: 'POST',
      body: converterForm,
    });

    if (!converterRes.ok) {
      const errBody = await converterRes.json().catch(() => ({ error: 'Converter error' }));
      return Response.json(
        { error: errBody.error ?? `Converter returned ${converterRes.status}` },
        { status: 502 },
      );
    }

    const raw = await converterRes.json();
    if (raw.error) {
      return Response.json({ error: raw.error }, { status: 422 });
    }

    // Map the converter response to our internal ImportedProjectData shape
    const mapped = mapAnalyzeResponse(raw, file.name);

    // ── INSERT PROJECT ──
    const [project] = await db
      .insert(projects)
      .values({
        ownerId: user.id,
        name: mapped.name,
        description: mapped.projectInfo?.['Project Title'] ?? null,
        status: 'active',
        settings: {},
      })
      .returning({ id: projects.id });

    const projectId = project.id;

    // ── INSERT PROJECT MEMBER (owner) ──
    await db.insert(projectMembers).values({
      projectId,
      userId: user.id,
      role: 'owner',
      displayName: user.name ?? null,
      photoUrl: user.avatarUrl ?? null,
    });

    // ── BATCH-INSERT TASKS ──
    // We need a stable DB-uuid per task so links can reference them.
    // The mapped tasks already have stable internal IDs (task-xxxxx), but the DB
    // uses uuid PKs generated by defaultRandom().  We resolve this by inserting
    // tasks one-by-one in order (preserving parent relationships) and building an
    // internalId → dbId map.  For large imports a single VALUES batch is faster,
    // but we need the DB-assigned IDs first — so we insert with explicit IDs via
    // the uuid() helper.  Since Drizzle does not expose nextval here, we generate
    // UUIDs ourselves using crypto.randomUUID().

    const internalToDbId = new Map<string, string>();

    if (mapped.tasks.length > 0) {
      const taskRows = mapped.tasks.map((t, i) => {
        const dbId = crypto.randomUUID();
        internalToDbId.set(t.id, dbId);
        // Cast to access runtime-only properties set by mapAnalyzeResponse
        const taskExt = t as typeof t & {
          isMilestone?: boolean;
          customText?: Record<string, string>;
        };
        return {
          id: dbId,
          projectId,
          parentId: null as string | null, // resolved in second pass
          name: t.name,
          startDate: t.start ?? null,
          finishDate: t.finish ?? null,
          duration: t.duration ?? null,
          durationUnit: 'd' as string,
          percentComplete: Math.round(t.percentComplete ?? 0),
          isMilestone: taskExt.isMilestone ?? false,
          isSummary: t.isSummary ?? false,
          wbs: t.wbs ?? null,
          outlineLevel: t.level ?? 0,
          status: t.status ?? null,
          customFields: (taskExt.customText ?? t.customAttributes ?? {}) as Record<string, unknown>,
          order: i,
        };
      });

      // Resolve parentId references now that we have the full internalToDbId map
      for (const row of taskRows) {
        const internalTask = mapped.tasks[taskRows.indexOf(row)];
        if (internalTask.parentId) {
          row.parentId = internalToDbId.get(internalTask.parentId) ?? null;
        }
      }

      // Insert in chunks to avoid hitting Postgres parameter limits
      const CHUNK = 500;
      for (let i = 0; i < taskRows.length; i += CHUNK) {
        await db.insert(tasks).values(taskRows.slice(i, i + CHUNK));
      }
    }

    // ── BATCH-INSERT LINKS ──
    if (mapped.links.length > 0) {
      const linkRows = mapped.links
        .map((l) => {
          const sourceTaskId = internalToDbId.get(l.source);
          const targetTaskId = internalToDbId.get(l.target);
          // Skip links where either end is unresolved
          if (!sourceTaskId || !targetTaskId) return null;
          return {
            projectId,
            sourceTaskId,
            targetTaskId,
            linkType: l.type as 'FS' | 'SS' | 'FF' | 'SF',
            lag: l.lag ?? 0,
            lagUnit: 'days' as string,
          };
        })
        .filter((r): r is NonNullable<typeof r> => r !== null);

      if (linkRows.length > 0) {
        const CHUNK = 500;
        for (let i = 0; i < linkRows.length; i += CHUNK) {
          await db.insert(links).values(linkRows.slice(i, i + CHUNK));
        }
      }
    }

    // ── BATCH-INSERT RESOURCES ──
    if (mapped.resources.length > 0) {
      const resourceRows = mapped.resources.map((r, i) => {
        // Cast to access runtime-only properties set by mapAnalyzeResponse
        const resExt = r as typeof r & { email?: string; group?: string };
        return {
          projectId,
          name: r.name,
          type: r.type ?? 'Work',
          email: resExt.email ?? null,
          order: i,
        };
      });

      const CHUNK = 500;
      for (let i = 0; i < resourceRows.length; i += CHUNK) {
        await db.insert(resources).values(resourceRows.slice(i, i + CHUNK));
      }
    }

    return Response.json({ projectId }, { status: 201 });
  } catch (err) {
    return authErrorResponse(err);
  }
}
